language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
jdk:
  - oraclejdk8
script:
  - ./gradlew assembleRelease  

before_deploy:       
  - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/horizon_move_demo.apk

